### ISSUE TITLE
cp command failing when elevating an asar packaged electron app

### ISSUE THREAD

**Issue by jviotti** [jorangreef/sudo-prompt#10]
`sudo-prompt` makes use of the `cp` command to perform a copy operation on the `applet.app` embedded in this module:

```js
/// https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L46
var command = '/bin/cp -R -p "' + source + '" "' + target + '"';
Node.child.exec(command, end);
```

When an electron application is packaged as an `asar`, the `cp` command will not be able to find the file and will throw the following error:

<img width="532" alt="screenshot 2016-02-08 10 32 15" src="https://cloud.githubusercontent.com/assets/2192773/12892949/e51968d8-ce64-11e5-9af4-9e7871dd30ca.png">

Is anything preventing us from implement this using Node's `fs` module instead, which is automatically patched by electron to understand `asar` archives by (extracting the file into a temporary location)?

**Comment by jviotti** [comment]
This looks like a good module to provide this operation: https://www.npmjs.com/package/ncp

I'll experiment with it and send a PR soon.

**Comment by jviotti** [comment]
I'm trying many modules to perform the copy but they all fail with weird errors:

- [fs.extra](https://github.com/coolaj86/utile-fs) and [wrench](https://github.com/ryanmcgrath/wrench-js):

<img width="532" alt="screenshot 2016-02-08 13 50 11" src="https://cloud.githubusercontent.com/assets/2192773/12894066/0473116a-ce6b-11e5-9b46-6e9b3bb8eab7.png">

Which means [Error -10810 Opening Applications or Relaunching Finder](http://www.thexlab.com/faqs/error-10810.html).

- [ncp](https://github.com/AvianFlu/ncp):

<img width="532" alt="screenshot 2016-02-08 14 16 14" src="https://cloud.githubusercontent.com/assets/2192773/12894680/afcde38e-ce6e-11e5-835c-106306402bea.png">

**Comment by jorangreef** [comment]
Thanks @jviotti, this should be fixed by https://github.com/jorangreef/sudo-prompt/commit/fe26a8a15937f28087b6ac80a0a636b5e8cf96b9

**Comment by jviotti** [comment]
@jorangreef Thanks for this. I'll give it a test and let you know how it goes.

**Comment by jviotti** [comment]
@jorangreef Works great, thanks again!
