### ISSUE TITLE
User did not grant access on windows 10 for administrator

### ISSUE THREAD

**Issue by gengshenghong** [jorangreef/sudo-prompt#104]
Hi,

I got "User did not grant access" directly without the UAC prompt.

And to be noted, it works on normal installation for my windows 10 (home installation). It only failed with my company computer, which is set as a domain user, and the user is administrator already. When I start "cmd.exe", it can run all administrator command directly. For my home installation, I think the user is also administrator, but if run "cmd.exe", by default it is not "administrator" and needs UAC. Any ideas? What will it happen with node-prompt if the user does not require UAC (in fact, in the company machine, I can use "process.exec" instead of "sudo-prompt.exec", but should sudo-prompt.exec just return ok directly? is this by design? If yes, do I need a way to check whether current user has admin permission....)

Hope it clear.

Thanks,
Shenghong

**Comment by jorangreef** [comment]
Thanks @gengshenghong 

> If yes, do I need a way to check whether current user has admin permission.

Yes, would you be able to see if you can find a fix for this?

**Comment by jorangreef** [comment]
@gengshenghong any luck?

**Comment by jorangreef** [comment]
Please re-open if you find a workaround.
