### ISSUE TITLE
Can i get the handler when button ok was clicked on Mac OS?

### ISSUE THREAD

**Issue by chaserstrong** [jorangreef/sudo-prompt#106]
Hello. Is there a way I can get a handler after i click the ok button on the prompt dialog?
Because my command is long-running and i should show this status on my web page.
![image](https://user-images.githubusercontent.com/18061322/65573950-a3f3c700-df9e-11e9-8960-e50df4b8d4f3.png)

**Comment by jorangreef** [comment]
Please see https://github.com/jorangreef/sudo-prompt/issues/54
