### ISSUE TITLE
Quit the process started by the prompt

### ISSUE THREAD

**Issue by hb1998** [jorangreef/sudo-prompt#108]
how to quit the process started by that prompt? since it runs as superuser `killall pname `or `kill pid` doesn't work and also even if you kill it from the terminal, App throws an error.
Also is there a way to retain the privileges once we got that from user.

OS: ubuntu
ENV: electron

**Comment by jorangreef** [comment]
Sorry @hb1998, neither of these are possible given the constraints, please see past issues:

https://github.com/jorangreef/sudo-prompt/issues/90
https://github.com/jorangreef/sudo-prompt/issues/74
https://github.com/jorangreef/sudo-prompt/issues/42
https://github.com/jorangreef/sudo-prompt/issues/48
https://github.com/jorangreef/sudo-prompt/issues/95
