### ISSUE TITLE
Clearing the "sudo" cache

### ISSUE THREAD

**Issue by jviotti** [jorangreef/sudo-prompt#11]
Is there a way to clear the `sudo` cache to force the prompt to appear? Maybe it's worth to document in the README since it can be quite helpful when debugging.

**Comment by jorangreef** [comment]
Yes there is, using regular sudo in a terminal:

`sudo -k`

I don't want to make it part of sudo-prompt's scope, but could you do a pull request for the README?

**Comment by jviotti** [comment]
@jorangreef Done! Let me know if you think the description can be rephrased in a better way.

**Comment by jorangreef** [comment]
Thanks! Could you just change "time stamp" to "timestamp"? I know the sudo man page uses "time stamp" but everywhere else it's usually just "timestamp".

**Comment by jviotti** [comment]
@jorangreef Sure, done!
