### ISSUE TITLE
options.env does not allow "(" and ")" characters

### ISSUE THREAD

**Issue by ranasaria** [jorangreef/sudo-prompt#111]
I am using sudo-prompt in a cross platform electron app that runs on mac, linux on windows. On windows machines the environment variable names have characters outside of /^[a-zA-Z_][a-zA-Z0-9_]*$/. So since sudo-prompt supports windows, it should allow all characters that a windows machine allows for environment variables.

**Comment by jorangreef** [comment]
Thanks @ranasaria. I am sorry but we only allow POSIX characters for security.

If you really need "(" and ")" you can always write out a temporary shell script and execute that with sudo-prompt.

**Comment by ranasaria** [comment]
How about on windows only we allow just the 2 variables: 

- ProgramFiles(x86)  
- CommonProgramFiles(x86)

As these are the two most common values that are a problem on the windows machines out of the box.
