### ISSUE TITLE
Source code of applet.app 

### ISSUE THREAD

**Issue by automation-stack** [jorangreef/sudo-prompt#14]
Is it possible to find somewhere the applet source code?

**Comment by jorangreef** [comment]
https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L360

**Comment by automation-stack** [comment]
@jorangreef  thanks, but there is a compiled code encoded as base64 string rather than source code?

**Comment by jorangreef** [comment]
Sure, you need to unzip the base64 string to recreate the applet.

See: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L177

**Comment by jorangreef** [comment]
It's just an applet, you can open the applet and view the source with Script Editor.

**Comment by automation-stack** [comment]
ok, thanks
