### ISSUE TITLE
Elevation error

### ISSUE THREAD

**Issue by loranger** [jorangreef/sudo-prompt#17]
As described in the issue [#289](https://github.com/resin-io/etcher/issues/289), I have an issue with [Etcher.app](http://www.etcher.io/).
It seems etcher uses sudo-prompt, but I cannot make it work because etcher is not able to grant requested sudo privileges.

As requested in the [etcher's issue](https://github.com/resin-io/etcher/issues/289), I tried the following test and the step 7 did prompt fo my password :

1. Open a Terminal window
1. `sudo -k`
1. `sudo mkdir -p /var/db/sudo/$USER`
1. `sudo touch /var/db/sudo/$USER`
1. Quit the Terminal window
1. Open another Terminal window
1. `sudo touch /var/db/sudo/$USER`

Maybe this issue is related to the [OS X 10.10.5 kernel local privilege escalation](https://news.ycombinator.com/item?id=10067524) issue I did fix by adding a `Defaults tty_tickets` in my `/etc/sudoers` ?

**node version**: v5.10.1
**npm version**: 3.8.6
**platform**: Darwin Merlin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 x86_64 (OS X 10.11.4)

**Comment by jorangreef** [comment]
Merging with https://github.com/jorangreef/sudo-prompt/issues/13.
