### ISSUE TITLE
Any plan for windows support?

### ISSUE THREAD

**Issue by leftstick** [jorangreef/sudo-prompt#27]
As title. I am wondering if you have any suggestion for windows?

**Comment by jorangreef** [comment]
I have not done it yet because `sudo-prompt` was meant as a prompt wrapper around `sudo` and the Windows elevation model is different. It can be done though. Would you be able to help with it?

**Comment by jorangreef** [comment]
Done: https://github.com/jorangreef/sudo-prompt/commit/a57487d444850826e7c87d5c8a4a4f1f9d689b20
