### ISSUE TITLE
Detecting availability of a graphical PolKit authentication agent

### ISSUE THREAD

**Issue by jviotti** [jorangreef/sudo-prompt#28]
I've seen some issues when running this module on GNU/Linux systems without a full featured desktop environment (e.g: Arch Linux + i3). In these kinds of systems, the user doesn't always have a graphical PolKit authentication agent, which causes `pkexec` to default to asking for the password using stdin, which won't be seen from the context of a desktop application.

I'd be great if we could make this module check if there is an available PolKit authentication agent, and default to other graphical sudo implementation, or throw a warning otherwise.

`ps aux` seems to output useful information about available authentication agents, but I bet there should be a more reliable way using PolKit tooling directly.

As an example, this is what I get on Ubuntu 16.04:

```
parallels@ubuntu:~$ ps aux | grep polkit
root       840  0.0  0.1 303876  6600 ?        Sl   07:35   0:10 /usr/lib/policykit-1/polkitd --no-debug
paralle+  3766  0.0  0.6 656268 27080 ?        Sl   07:36   0:02 /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
paralle+ 28096  0.0  0.0  15940   944 pts/10   S+   21:37   0:00 grep --color=auto polkit
```

**Comment by jviotti** [comment]
After some investigation, there doesn't seem to be a way to reliably list the available authentication agents. This is stored in memory by the PolicyKit backend, and there is no public API to query it.

`pkexec` is supposed to exit with an error if we pass `--disable-internal-agent` (which we already do). I guess we can check if `stderr` contains `No authentication agent found.` and translate appropriately.

**Comment by jorangreef** [comment]
Thanks @jviotti

**Comment by jviotti** [comment]
Thank you @jorangreef !
