### ISSUE TITLE
Add ability to set SUDO_ASKPASS to bundled MacOS applet

### ISSUE THREAD

**Issue by ezekg** [jorangreef/sudo-prompt#32]
It would be great if you could export a function that returns a permanent path to the bundled applet for MacOS, so that the `SUDO_ASKPASS` environment variable can be set to use it. I have several third-party scripts that use `sudo -A` if a tty isn't present, and right now they're timing out.

**Comment by ezekg** [comment]
Upon further investigation, this probably isn't possible seeing as the applet doesn't return the password in plaintext, which is what the `SUDO_ASKPASS` variable expects the script to do.

**Comment by jorangreef** [comment]
Yes, the applet just delegates elevation to the OS. Also, I think that using `SUDO_ASKPASS` would require the applet to be executed by `sudo` directly, whereas the applet does quite a few things beyond just elevation (`stdout`, `stderr`, status code handling etc.) and is designed to be executed by `sudo-prompt`.
