### ISSUE TITLE
restart electron app as root

### ISSUE THREAD

**Issue by mnewmedia** [jorangreef/sudo-prompt#34]
When i try to restart the app as root i get the error `Error: User did not grant permission`, although I did enter the password and clicked the OK button. 
```js
// ... imports
var sudo = require('sudo-prompt');
const app = require('electron').remote.app;
console.log('app exe', app.getPath('exe'));

// ... check if started programm as root
var user = process.env['USER'];
if (user === 'root' || user === 'administrator') {
    console.log('started as root');
} else {

    // try restarting as root
    sudo.exec(app.getPath('exe'), {name: 'Appname'}, function(error, stdout, stderr) {
        stdout && console.log('output:', stdout);
        stderr && console.log('error:', stderr);
        error && console.log('error:', error);
        if (!error) {
            app.exit(0)
        } else {
            // Error: User did not grant permission
            alert('Sorry we could not restart the app with administrator/root privileges, which is necessary for certain functions.');
        }
    });
}
```

Any ideas?

But no matter what, thank you so much for creating this!

---

I really do not know a lot of linux, but i thought with try and error it may works. But finally giving up, all failed:
```js
t = 'script/to/start.sh';
startNew(t);
startNew(app.getPath('exe'));
startNew(t + ' &');
startNew(app.getPath('exe') + ' &');
startNew('nohup ' + t);
startNew('nohup ' + app.getPath('exe'));
startNew('nohup sudo ' + t + ' &');
startNew('nohup sudo ' + app.getPath('exe') + ' &');

startNew('fork || exec "' + app.getPath('exe') +'"'); // starts at least the app new, but not as root :(
startNew('echo "" | fork || exec sudo -S "' + app.getPath('exe') +'"');
startNew('sudo -S fork || exec "' + t +'"');
startNew('exec "' + app.getPath('exe')  + '"');
startNew('exec "' + t  + '"');
```

---

ok, got it i should learn to read the readme and look into the closed issues #15 ;) `non-graphical terminal commands only`. But if somebody has an idea let me hear it.

**Comment by jorangreef** [comment]
Thanks @mnewmedia 

Which platform is this, and what version?

Can you try changing into the `node_modules/sudo-prompt` directory and then running `node test.js`?

**Comment by mnewmedia** [comment]
Ubuntu 16.04. test works and all other commands are also working just not the to restart the electron-app, but thats's probably because of ` non-graphical terminal commands only` #15.

**Comment by jorangreef** [comment]
Yes, it's not a good idea to run graphical commands using sudo or sudo-prompt. You can try using `pkexec` or `gksudo` directly on Linux for that.

**Comment by mnewmedia** [comment]
So then thanks anyway! repeat with me: i will read the readme, i will read the readme.. haha
