### ISSUE TITLE
How do I get the pid after using sudo prompt?

### ISSUE THREAD

**Issue by SxMShaDoW** [jorangreef/sudo-prompt#35]
Currently we are using sudo prompt in parts of our application.

Is is there a way to return the pid of a process that is started with sudo prompt, so we can store it. 

The value: We would like an easy way to also shutdown / verify all things started with sudo prompt are shutdown properly. If we have the pid it would be easier to kill it. 

Open to other suggestions (as we currently using grep)

**Comment by jorangreef** [comment]
We currently don't provide the pid of the launched process.

We could provide the pid of the launched process, but depending on the platform we use a few shells to launch the process, so if it were to be used for verifying shutdown then there's actually several pids that would be involved, there's the potential for race conditions with these too. Some interim launch processes might be short lived so by the time we pass the pid to your application, the pid might refer to another process.

To keep it simple, I would recommend sticking with grep if that's fine?
