### ISSUE TITLE
User-names with a "-"

### ISSUE THREAD

**Issue by Silve2611** [jorangreef/sudo-prompt#36]
User-Names with an "-" are possible on mac but not allowed by the validation check. Exchanging [a-z0-9 ] with [a-z0-9 -] solves it for mac. Although I do not know if it is causing problems on other systems. 

`function ValidName(string) {
  // We use 70 characters as a limit to side-step any issues with Unicode
  // normalization form causing a 255 character string to exceed the fs limit.
  if (!/^[a-z0-9 -]+$/i.test(string)) return false;
  if (string.trim().length === 0) return false;
  if (string.length > 70) return false;
  return true;
}
`

**Comment by jorangreef** [comment]
Which version of `sudo-prompt` are you using?

`ValidName()` is only used to validate the display name of the process requesting permission, not a username.
