### ISSUE TITLE
Doesn't ask for permissions second time

### ISSUE THREAD

**Issue by debelop13** [jorangreef/sudo-prompt#41]
Hello,

I am having a problem with asking permissions:

- Yosemite 10.10 (in Sierra I don't have this problem, ask always for permissions)
- User without admin privileges
- Compiled .app with Electron.

First time that app is opened, works correctly, but second time sudo-prompt don't ask for user and password, and obviously, fails. I have to restart, and then it is called again.

My command is:
sudo chown -R User '/Applications/Example/Plugins/'
var command = "chown -R User '/Applications/Example/Plugins/'";
sudo.exec(command,....

It is showing this message:
Command failed: /usr/bin/sudo -n -E -- chown -R User '/Applications/Example/Plugins/'
User is not in the sudoers file.  This incident will be reported.

Command is working correctly in shell, that asks for password every time.

Thanks.

**Comment by jorangreef** [comment]
It looks like the `User` you are passing does not exist as a valid user on the system.

**Comment by debelop13** [comment]
I have create a new user, without admin privileges, and is continuous happening. I have to restart or log out and it works again, but only first time.

**Comment by jorangreef** [comment]
Your command (`chown -R User`) shows that you are passing in `User` literally as your user name?

**Comment by jorangreef** [comment]
What does `ls /Users` return on that system?

**Comment by debelop13** [comment]
I do a whoami, my user is named "test". 

My real code
var user = execSync("whoami").toString().replace("\n", "");
var command = "chown -R " + user + " '" + destination + "';
sudo.exec(command, options,.....

It is like my chown destroys something 

First time after run my app:

Admins-MacBook-Pro:~ test$ /usr/bin/sudo -n -E -- chown -R test '/Applications/Example/Plugins/'
sudo: a password is required
Admins-MacBook-Pro:~ test$ ls /Users
Shared	admin	test


After run my app:

Admins-MacBook-Pro:~ test$ /usr/bin/sudo -n -E -- chown -R test '/Applications//Example/Plugins/'
test is not in the sudoers file.  This incident will be reported.
Admins-MacBook-Pro:~ test$ ls /Users
Shared	admin	test


Curiosuly I dont need to restart, 5 minuts later open application, I run again and works fine. 
Restart / 5 minuts after.. (only in yosemite):

Admins-MacBook-Pro:~ test$ /usr/bin/sudo -n -E -- chown -R test '/Applications/Example/Plugins/'
sudo: a password is required
Admins-MacBook-Pro:~ test$ ls /Users
Shared	admin	test

**Comment by jorangreef** [comment]
Thanks, if you are logged in as the `test` user, what does running `id` in the Terminal return (make sure you are logged in as the `test` user)?

**Comment by debelop13** [comment]
Yes, i am logged in test user:

Before run my app:

Admins-MacBook-Pro:~ test$ /usr/bin/sudo -n -E -- chown -R test '/Applications/Adobe Photoshop CC 2015.5/Plug-ins' '/Library/Application Support/Adobe/CEP/extensions' 
sudo: a password is required
Admins-MacBook-Pro:~ test$ id
uid=503(test) gid=20(staff) groups=20(staff),703(com.apple.sharepoint.group.3),12(everyone),61(localaccounts),702(com.apple.sharepoint.group.2),100(_lpoperator),701(com.apple.sharepoint.group.1)


After run my app:

Admins-MacBook-Pro:~ test$ /usr/bin/sudo -n -E -- chown -R test '/Applications/Adobe Photoshop CC 2015.5/Plug-ins' '/Library/Application Support/Adobe/CEP/extensions' 
test is not in the sudoers file.  This incident will be reported.
Admins-MacBook-Pro:~ test$ id
uid=503(test) gid=20(staff) groups=20(staff),703(com.apple.sharepoint.group.3),12(everyone),61(localaccounts),702(com.apple.sharepoint.group.2),100(_lpoperator),701(com.apple.sharepoint.group.1)

**Comment by jorangreef** [comment]
I think the problem is that your `test` user is not a member of the `admin` group. Your default sudoers file will probably only allow `root` and users who are members of the `admin` group. You need to add your `test` user to the `admin` group (this may work: http://apple.stackexchange.com/questions/76088/how-do-i-give-a-user-sudo-permissions).

**Comment by debelop13** [comment]
But this can be solved in my mac, but If I have to distribute this app, it is a problem..

**Comment by jorangreef** [comment]
If you restart your computer, and without running the app, what does the following give?

`/usr/bin/sudo -E -- chown -R test '/Applications/Example/Plugins/'`

**Comment by debelop13** [comment]
The same that if I wait 5 minuts..

If I restart, works correctly, and doesn't show sudoers file error:

Admins-MacBook-Pro:~ test$ /usr/bin/sudo -n -E -- chown -R test '/Applications/Example/Plugins/'
sudo: a password is required

Is how the module would be blocking this command during a few minutes..

**Comment by debelop13** [comment]
Sorry, I did not understand correctly last comment, and I have delete it.

----

This command is asking for password, and after error is the same:

Admins-MacBook-Pro:~ test$ /usr/bin/sudo -E -- chown -R test '/Applications/Example/Plugins/'
Password:
test is not in the sudoers file.  This incident will be reported.

**Comment by jorangreef** [comment]
Thanks, running the command I gave you confirms that the issue is either with `sudo` or `chown`. To see which one it is...

Can you try and run this command in your Terminal:

`sudo -k && whoami && sudo echo hello`

And then try this:

`sudo -k && sudo chown -R test '/Applications/Example/Plugins/'`

What do these two commands return?

**Comment by debelop13** [comment]
Can be possible the same error? 

Admins-MacBook-Pro:~ test$ sudo -k && whoami && sudo echo hello
test
Password:
test is not in the sudoers file.  This incident will be reported.

Admins-MacBook-Pro:~ test$ sudo -k && sudo chown -R test '/Applications/Example/Plugins/'
Password:
test is not in the sudoers file.  This incident will be reported.

**Comment by jorangreef** [comment]
How did you create the `test` user on your Mac?

I think it's because your `test` user is not a member of the `admin` group, or perhaps because of how the user was created.

There's nothing that `sudo-prompt` can do since your command fails with `sudo` itself. `sudo-prompt` can only do what `sudo` can do.
