### ISSUE TITLE
Get Error code when run error command

### ISSUE THREAD

**Issue by hieund-hblab** [jorangreef/sudo-prompt#46]
Hey guys,
Someone please help me how to get ERROR CODE when run command error?
Thanks!

**Comment by jorangreef** [comment]
Thanks, this should fix it: https://github.com/jorangreef/sudo-prompt/commit/810e87f9baef220702d268b2b76573533c795127

Please let me know.

**Comment by jorangreef** [comment]
If the process was run and exited with an error code, then we now add the error code to the error object in the same way that Node's `child_process.exec()` does. You can access it using `error.code`. It may be `undefined` if the process was not started, or a string e.g. 'ENOENT' if something went wrong along the way to starting the process, or an integer.

**Comment by hieund-hblab** [comment]
hi @jorangreef ,
That is good, it work fine now.
Thankyou so much!
