### ISSUE TITLE
Store password for next time run command

### ISSUE THREAD

**Issue by hieund-hblab** [jorangreef/sudo-prompt#48]
Hey guys,
Someone please help me know how to store password for next time run command?
(my app alway ask permission when run any command, it is not good for UI)
Thanks!

**Comment by hieund-hblab** [comment]
please help me,
have any config for above issue?
Thanks!

**Comment by jorangreef** [comment]
Thanks @hieund-hblab, would you take a look at these issues:

https://github.com/jorangreef/sudo-prompt/issues/42

https://github.com/jorangreef/sudo-prompt/issues/43

I think you are using `sudo-prompt` on a system with TTY tickets enabled. This requires sudo to prompt for a password for every new shell session (i.e. per `sudo.exec()` call).

I would recommend batching your commands into a single script and then running that with `sudo-prompt`, or else trying some of the suggestions in those issues.

**Comment by hieund-hblab** [comment]
okay, thanks!

**Comment by kounelios13** [comment]
Is there any way to disable TTY tickets on startup?

**Comment by jorangreef** [comment]
Take a look at:

https://serverfault.com/questions/111064/sudoers-how-to-disable-requiretty-per-user

https://unix.stackexchange.com/questions/79960/how-to-disable-requiretty-for-a-single-command-in-sudoers
