### ISSUE TITLE
Can i rename dialog when windows os asked permission?

### ISSUE THREAD

**Issue by tinvm** [jorangreef/sudo-prompt#49]
Hi Joran,

Many thanks for creating the package. It's very handing with us.
However, on windows os, when running this lib, windows asks permission as "exe.cmd" name. Have we optioned for a set this name? Thanks

**Comment by jorangreef** [comment]
Thanks @tinvm 

On Windows, there is no way to set the name at present.

**Comment by tinvm** [comment]
Thanks @jorangreef for your answer.
on osx, can i set it?
and pls tell me how about package call cmd!

**Comment by jorangreef** [comment]
On OS X you can set the `name` as per the README instructions: https://github.com/jorangreef/sudo-prompt#usage

On Windows, we use cmd.exe as a shell to run the elevated process, that's why it appears as the name.

**Comment by tinvm** [comment]
@jorangreef  Yep! thanks, nice to run on OS-X.
we have some command line script which has an argument and need run on the system.
Are there any ways to pass cmd and run on the system?

**Comment by hieund-hblab** [comment]
@jorangreef 
Thanks for your support, but I have one question:
Did this module was based on chikd_process of node.js (https://nodejs.org/api/child_process.html)?
Please help me, thanks!

**Comment by jorangreef** [comment]
Thanks @hieund-hblab I am not sure if I understand what you are asking. The module does use child_process in the implementation, but the interface of the module is not meant to be as full featured as child_process.

**Comment by hieund-hblab** [comment]
@jorangreef I got it.
Thank you so much!
