### ISSUE TITLE
support more platforms =)

### ISSUE THREAD

**Issue by mnewmedia** [jorangreef/sudo-prompt#5]
was frustradet, asked google
found it, was so happy
tried it with so much hope
not supported, so sad...

**Comment by jorangreef** [comment]
Any platform in particular?

**Comment by mnewmedia** [comment]
fedora linux =)

**Comment by gamedevsam** [comment]
I'm using Ubuntu Linux and also need this, I will pay you a reasonable bounty for it (BTC or PayPal).

**Comment by jorangreef** [comment]
I am working on this now.

Please let me know if you can run either of the following in Fedora or Ubuntu:

`pkexec echo testing`

`gksudo echo testing`

**Comment by jorangreef** [comment]
There's a new major release with beta support for Linux (tested on Ubuntu). Please test and let me know how it works on your Linux.

**Comment by jorangreef** [comment]
Closing with https://github.com/jorangreef/sudo-prompt/commit/57a83efd64993fdc5ae05fa39feea73820f070af
