### ISSUE TITLE
Ampersand Character in Windows User Directory

### ISSUE THREAD

**Issue by josephphayden** [jorangreef/sudo-prompt#52]
Hey,

Thanks a lot for producing this package, super-helpful!

I've run into an issue when running a command on a Windows machine where the user folder contains an ampersand. Please see the logs below.

From what I can see in your code the path is already wrapped in double-quotes?!

Let me know if you need any more information or help.

Thanks!

~~~
Command failed: powershell.exe Start-Process "C:\Users\MARK&R~1\AppData\Local\Temp\fe6c94de20f19bcf3d07c504ca9012d1\execute.bat" -WindowStyle hidden -Verb runAs
At line:1 char:28 Start-Process C:\Users\MARK&R~1\AppData\Local\Temp\fe6c94de20f19bcf3d ...

The ampersand (&) character is not allowed. The & operator is reserved for future use; wrap an ampersand in double quotation marks ("&") to pass it as part of a string.
~~~

**Comment by jorangreef** [comment]
Thanks @josephphayden !

I am sorry for not getting back to you sooner. I will try and reproduce and work on a fix. I am away for a few days and then will sort it out.

**Comment by jorangreef** [comment]
I reproduced the issue and this should be fixed properly by https://github.com/jorangreef/sudo-prompt/commit/a7338f638c43afb536d4d19d502ff5157395c91d

Thanks again for spotting this.
