### ISSUE TITLE
Add support for spawning long-running processes

### ISSUE THREAD

**Issue by DSBalaban** [jorangreef/sudo-prompt#54]
Node's `exec` isn't suitable for long-running processes due to that max buffer size.

Will there be an issue launching a process that could stay alive 24/7 through `sudo-prompt`, since there is no support for `spawn`? As in, does `sudo-prompt`'s `exec` work differently?

**Comment by jorangreef** [comment]
You are right about the max buffer limit.

If you need to launch a long-running process, you can always launch it as its own process, disconnected from the parent, and use files to get the stdout and stderr yourself.

For example:

```
nohup node script.js 2>&1 >> log &
```

It would be good to support `spawn` but we don't have that yet.

**Comment by DSBalaban** [comment]
Considered doing that, but hadn't thought of tapping into logs like that myself. Thank you, @jorangreef!
