### ISSUE TITLE
how to make sudo-prompt works with NOPASSWD in /etc/sudoers

### ISSUE THREAD

**Issue by icymind** [jorangreef/sudo-prompt#58]
```bash
simon.mbp: ~
🍉  sw_vers
ProductName:    Mac OS X
ProductVersion: 10.11.6
BuildVersion:   15G1611

simon.mbp: ~
🍉  sudo cat /etc/sudoers
...
ALL   ALL=(ALL) NOPASSWD: /usr/sbin/networksetup, /sbin/route
...
```

I can execute `sudo /sbin/route` command in terminal without password. But "sudo-prompt" require password when execute the same command.

Any advice?

**Comment by jorangreef** [comment]
Does `sudo-prompt` ask for a password and then correctly call your command?

**Comment by icymind** [comment]
yes it did. but what I expect is:
- ask for password when command doesn't list in sudoers
- run silently when command config with 'NOPASSWD'

**Comment by jorangreef** [comment]
Thanks @icymind 

What does the following return?

1. Open a brand new Terminal window.
2. Run `sudo -n echo hello`

**Comment by icymind** [comment]
Thanks for your reply. When I run your command, it just print 'sudo: a password is required' then exit.

```bash
🍉  sudo -n echo hello
sudo: a password is required

simon.mbp: ~ 
🍉   
```

more info, `child_process` works as expect, it didn't require a password :
```js
const cmd = 'sudo /sbin/route change default "192.168.10.1"'
require('child_process').exec(cmd, {}, (err, stdout, stderr) => {
  if (err) {
    console.error(err)
  } else {
    console.log(stdout, stderr)
  }
})
```

**Comment by jorangreef** [comment]
Before asking for a password, `sudo-prompt` calls `sudo -n`.

This instructs `sudo` to run the command if a password is not required (if a sudo session is already established), or else to return the `a password is required` error.

If we see the error, we then ask the operating system to request administrator privileges on our behalf.

The issue here is that `sudo` itself is saying a password is required, yet when you run `sudo` without `-n` no password is actually required.

**Comment by jorangreef** [comment]
I am going to close this issue if it's fine with you:

1. `sudo` itself is giving us the wrong feedback (saying a password is required when your sudoers says otherwise).

2. It is unusual to allow password-less sudo privileges.

3. `sudo-prompt` is technically still working correctly by requesting administrator privileges, and executing your command.

**Comment by icymind** [comment]
so, there is no way to run a `sudo` command beyond a sudo session?

sorry for bothering you.

**Comment by jorangreef** [comment]
> so, there is no way to run a sudo command beyond a sudo session?

No, none that I know of. You could take this issue up with the developers of `sudo`.

> sorry for bothering you.

Anytime, let me know if you have any other questions.

**Comment by icymind** [comment]
sorry, I still feel confused.

I think the reason why terminal reports error when I run `sudo -n echo hello` is that echo doesn't config as `NOPASSWD`

But `/sbin/route` is different, I successfully execute it in a new terminal:
```bash
simon.mbp: ~ 
🍉  sudo -n /sbin/route change default "192.168.10.1"
change net default: gateway 192.168.10.1
```

Please let me know if I misunderstanding

**Comment by jorangreef** [comment]
What does the following return?

```
sudo -k
sudo -n /sbin/route change default "192.168.10.1"
```

**Comment by icymind** [comment]
```bash
simon.mbp: ~ 
🍉  sudo -k
sudo -n /sbin/route change default "192.168.10.1"
change net default: gateway 192.168.10.1
```
It execute without error.

**Comment by jorangreef** [comment]
Ah, thanks I see.

`sudo -n` is in fact checking your `/etc/sudoers` and seeing that no password is required for `/sbin/route`.

There should be no difference between that last command you tried and what `sudo-prompt` does (except for the `-E` flag that `sudo-prompt` also adds)?

See: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L11

If `/usr/bin/sudo -n -E -- /sbin/route change default "192.168.10.1"` succeeds, then `Attempt()` will finish immediately without calling `Mac()` (which is where we request administrator privileges).

**Comment by icymind** [comment]
```bash
simon.mbp: ~
🍉  /usr/bin/sudo -n -E -- /sbin/route change default "192.168.10.1"
sudo: sorry, you are not allowed to preserve the environment
```
Then I add 'SETENV' to /etc/sudoers as what https://superuser.com/questions/636283/how-to-allow-user-to-preserve-environment-with-sudo/687347 says, now sudo-prompt runs well. 

Is it a better solution to offer an option to toggle '-E' flag?  When we use `sudo`, we don't use `-E` flag offen, isn't it?

**Comment by jorangreef** [comment]
We had an issue in the past regarding not having the `-E` flag, see: https://github.com/jorangreef/sudo-prompt/issues/20.

I would rather try and preserve environment variables than not.

**Comment by icymind** [comment]
OK, Thanks your work!

**Comment by bighitbiker3** [comment]
I realize this thread is super old, but for some reason I can't get this to honor NOPASSWD, nor can I find the `sudo -n` call in the source code for this library. Did that get nixed sometime in the past few years?
