### ISSUE TITLE
User did not grant permission

### ISSUE THREAD

**Issue by DSBalaban** [jorangreef/sudo-prompt#59]
Using **elementary OS 0.4.1** (based on **Ubuntu 16.04**) over here.

I'm trying to run a bash script via `sudo-prompt.exec`, and after entering my password the app throws an error saying **User did not grant permission**.

Script would be launched from an Electron environment, if that is at all important. The GUI application itself is _NOT_ run with administrator privileges.

I know it's not much to go on, but I've no idea what could be wrong and was hoping to get some pointers (again :smile: )

**Comment by jorangreef** [comment]
Thanks @DSBalaban would you be able to add a `console.log(error)` statement to the source in `index.js` over here: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L130 and let me know what you get?

Also the the output of `stdout` and `stderr` which `sudo-prompt` returns to your callback.

**Comment by DSBalaban** [comment]
@jorangreef Thanks for replying. 

I'll see if I can reproduce the error, as I'm no longer seeing it (magic, I tell you). Give me a bit of time.

**Comment by jorangreef** [comment]
Sure, sorry for the late reply.

I will close in the mean time then if that's fine with you.

**Comment by ravikp7** [comment]
Hi @jorangreef I think I've got a similar issue. I'm also running a script from electron environment using `sudo-prompt.exec` from the app which is run without sudo permissions. 
Everything works fine, no errors during development. The app works fine on mac with dmg built by electron-builder. Also no error with unpacked linux build from electron-builder. 
I'm only having issues with AppImage (again built by electron-builder) on linux. Sudo-prompt throws this error after entering the password
`
Error: Command failed: "/usr/bin/pkexec" --disable-internal-agent env ELECTRON_RUN_AS_NODE=1 IPC_SERVER_ID=BB-server-17137 IPC_CLIENT_ID=BB-client-17137 /tmp/.mount_ASpV7H/usr/bin/beagleboot /tmp/.mount_ASpV7H/usr/bin/resources/app.asar/lib/elevate.js
/usr/bin/env: ‘/tmp/.mount_ASpV7H/usr/bin/beagleboot’: Permission denied
`
Seems that the executable isn't accessible. Any suggestions, where it's going wrong?

**Comment by ravikp7** [comment]
I found the cause of this issue. AppImages are mounted using FUSE, which only allows execution permissions on the mounted image to the user that actually executed the image. So, su can't execute with it. I'd have to remount the AppImage as root to get it working.

**Comment by jorangreef** [comment]
Thanks @ravikp7

**Comment by probonopd** [comment]
> I found the cause of this issue. AppImages are mounted using FUSE, which only allows execution permissions on the mounted image to the user that actually executed the image. So, su can't execute with it. 

Check what the Etcher AppImage, which requires root, is doing. It's described at https://github.com/AppImage/AppImageKit/issues/268#issuecomment-280027991
