### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by jviotti** [jorangreef/sudo-prompt#6]
Hi,

I've been using `sudo-prompt` for a couple of days in an Electron application, however it suddenly started failing with the following error:

```sh
$ npm start

> herostratus@0.0.1 start /Users/jviotti/Projects/resin/herostratus
> electron lib/herostratus.js

Command failed: /bin/sh -c sudo -n /Users/jviotti/Projects/resin/herostratus/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron lib/herostratus.js
env: node\r: No such file or directory
```

Code:

```js
sudoPrompt.setName('Herostratus');
sudoPrompt.exec(process.argv.join(' '), function(error) {
  if (error) {
    console.error(error.message);
    process.exit(1);
  }

  // Don't keep the original parent process alive
  process.exit(0);
});
```

The command that files is this one: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L30, however by running it manually myself I can see it gives the expected output:

```sh
$ sudo -n /Users/jviotti/Projects/resin/herostratus/node_modules/electron-prebuilt/dist/Electron.app/Contents/MacOS/Electron lib/herostratus.js
sudo: a password is required
```

Is there a way a carriage return is slipping in any `env node` hash bang?

**Comment by jviotti** [comment]
After some investigation, running the application that uses `sudo-prompt` directly (with `node`, `electron`, `coffee`) works fine, however the issue is reproducible when calling the script from an npm script.

**Comment by jorangreef** [comment]
Thanks @jviotti I will be away until next week and will look into it when I get back.

**Comment by jviotti** [comment]
@jorangreef I've found the root of the issue.

My application uses [windosu](https://github.com/tehsenaus/windosu) to elevate permissions on Windows. This module exposes a `sudo` command, which get's installed in `node_modules/.bin`.

When calling a npm script, npm adds `node_modules/.bin` to the path, so when `sudo-prompt` executes `sudo -n <command>` it actually executes windosu's `sudo` instead of the system one. The latter happens to have `\n\r` line endings, ultimately throwing the initial error mentioned in the issue.

I'll mark `windosu` as an optional dependency in my application to avoid it being installed in other operating system than Windows, but I think we can improve `sudo-prompt` to avoid this issue by searching for the "system"'s `sudo`, which would make the module stronger and avoid someone else spending half day debugging the issue :)

I'm thinking we can change `sudo -n` to `/usr/bin/sudo`, which seems to be a quite standard location.

What do you think?

Happy to send a pull request.

**Comment by jorangreef** [comment]
Merged. Thanks @jviotti.

**Comment by jviotti** [comment]
@jorangreef Awesome, thanks for the NPM publish!
