### ISSUE TITLE
Using regional characters

### ISSUE THREAD

**Issue by dulebap** [jorangreef/sudo-prompt#60]
Module is really great but unfortunately on Windows it has problem with regional characters. It cannot find files in path. In Powershell on my computer I have encoding OEM 852. Javascript use utf-8 encoding and it is used to save .bat files in this module. I think it cause in differences in regional characters like Polish ąę or Danish å. 
I tried saving command.bat  encoded to OEM 852 (i provided encoded buffor instead of string with null encoding part) but it  didn't helped. I also tried adding chcp 1252 or chcp 65001 commands to change encoding in Powershell instance to UTF-8 but it hasn't helped either.
I've commented out removing files to check them manually in temp localization. chcp works fine when i run just command.bat. Problems start only when it is run like in extension from another .bat file. 
I've tried running only command.bat from powershell with -Verb runAs option but then I get error with info that user didn't provided access, but there wasn't any UAC prompt. 
Do you have any ideas how to fix problem with regional characters?

**Comment by jorangreef** [comment]
Thanks @dulebap 

Could you provide me with a bare minimum test script to reproduce?

Is your Windows setup custom configured (e.g. your shell encoding setup)?

While we are at it, would you mind checking if this is Windows only or can you find a way to reproduce this on other platforms?

**Comment by dulebap** [comment]
I didn't changed anything in shell encoding setup. I have Windows 10 with display language English,but with Polish(Programmers) Keyboard layout. My Powershell and cmd has 852 (OEM - Latin II) code page set as default (as I said I didn't changed settings myself).
The bare minimum test script to reproduce is for example 
var sudo = require('sudo-prompt');
sudo.exec("'C:\\sampleFolderą\\sampleProgram.exe'", function(error, stdout, stderr) {
        console.log(error);
      });
It is important to put some regional letter like "ą" in path.

I can try to reproduce this error on Mac later, or check how it works on Win 7 and Win 8. I let you know as soon as I manage to do so.

**Comment by dulebap** [comment]
On Win 7 and Win 8 behaviour is the same as on Win 10. Tomorrow I should have possibility to test it on Mac. Have you managed to reproduce error on your side?

**Comment by jorangreef** [comment]
Thanks @dulebap 

I can reproduce on my side on Windows 10 at least.

Can you create a plain `.bat` file with the following contents (or your actual command) and post the results?

```
C:\sampleFolderą\sampleProgram.exe
```

So above your `.bat` file contains only a single command (sampleProgram.exe). I think this is the bare minimum test case to reproduce.

**Comment by dulebap** [comment]
Thanks @jorangreef 

When encoding of command.bat was set to ansii I got:
C:\sampleFolder╣\sampleProgram.exe
The system cannot find the path specified.

When encoding was set to utf-8:
C:\sampleFolder─ů\sampleProgram.exe
The system cannot find the path specified.

When I set encoding in Notepad++ to OEM 852 the command runs fine. It means that probably when I tried to encode command generated by sudo-prompt to OEM 852 something went wrong?

**Comment by jorangreef** [comment]
Great, try the same `.bat` file but this time add this line at the top of the .bat file (as the first line):
```
chcp 65001
```

**Comment by dulebap** [comment]
I've got:
C:\praca>chcp 65001
Active code page: 65001

C:\praca>\sampleFolderą\sampleProgram.exe 9002 "C:\sampleFolderą"
It looks like it works fine in that case (utf-8 encoding in bat file).

**Comment by jorangreef** [comment]
Thanks for your help with testing. I will have a fix soon.

**Comment by jorangreef** [comment]
Fixed by https://github.com/jorangreef/sudo-prompt/commit/6a0577a387410763a28184b5f30d376e73fcb9b4

Please try out version 8 and let me know how it goes!

**Comment by dulebap** [comment]
It works now. I've tried adding chcp 65001 in wrong place, by myself in that case. 
Thanks for that fix.
