### ISSUE TITLE
Execute bash file?

### ISSUE THREAD

**Issue by GregTheGreek** [jorangreef/sudo-prompt#61]
Instead of executing a line of code can I execute a file?

**Comment by jorangreef** [comment]
Sure, you can call `exec()` on any executable file by passing the path to the file, just like you can with Node's `exec()`.

**Comment by GregTheGreek** [comment]
@jorangreef I'm getting an issue with this.. my line of code
`    sudo.exec(`sh ./script.sh`, options, function(error, stdout, stderr) `
I get an error:

`An error occured: Error: Command failed: /usr/bin/sudo -n -E -- sh ./script.sh' sh: ./script.sh: No such file or directory`

I'm not sure why but it seems to be looking for the file in the sudo directory instead of the current one.
