### ISSUE TITLE
Add tags for releases

### ISSUE THREAD

**Issue by streeter** [jorangreef/sudo-prompt#62]
Hi there, do you think you could add git tags for the releases? It looks like 30cd59a0c51e24b16135aeb02cb66068d632dbc1 is 7.1.1 and ebb21118e6cad962834ebfcd5b20008504911a24 is 8.0, but it's harder to figure out what code corresponds to which version without tags.

Thanks!

**Comment by jorangreef** [comment]
Thanks for the suggestion.

**Comment by jorangreef** [comment]
I double-checked and the releases should already all be tagged.

Try cloning https://github.com/jorangreef/sudo-prompt and then running `git tag`.

You should see all the tags corresponding to each release.

**Comment by jorangreef** [comment]
Ah, I see tags are on my machine but they are not made available when cloning...

**Comment by jorangreef** [comment]
Fixed, thanks!

**Comment by streeter** [comment]
Awesome, thank you!
