### ISSUE TITLE
packaging issue

### ISSUE THREAD

**Issue by irfman12** [jorangreef/sudo-prompt#65]
I need some help, I'm unable to get sudo prompt work from my packaged electron app.

It works fine when I run it in dev mode, but not with the exe. 

I'm not sure, if sudo-prompt is not being picked up, or something else.  it works fine in packaged form.

![image](https://user-images.githubusercontent.com/645130/34220795-e1d174da-e583-11e7-81ea-2f6ff8f8a440.png)

**Comment by jorangreef** [comment]
Thanks @irfman12, are you sure this is a `sudo-prompt` issue? It looks like the `toString` exception is being raised in your callback given to `sudo-prompt`. In other words, `sudo-prompt` calls your callback, and something in your callback is calling `toString()` on something which is `undefined`.

**Comment by irfman12** [comment]
in this situation, I'm trying to execute the stdout.toString(), stdout is coming as undefined by the exec function, I found that if my node modules are packaged in ASAR archive it's not working . do you have support for ASAR when sudo-prompt is packaged as part of executable in electron exe

**Comment by jorangreef** [comment]
sudo-prompt definitely supports being packaged as part of an asar archive.

I think you may be ignoring the `error` parameter passed to your callback.

If an `error` is returned to your callback then `stdout` will be undefined.
