### ISSUE TITLE
Works with electron-builder on Mac

### ISSUE THREAD

**Issue by erguotou520** [jorangreef/sudo-prompt#67]
It's ok in development, but flashed back in production.
I use `electron-builder` to build my electron project to `dmg` on Mac. But it flashed back after running, no dialog prompted for password.

**Comment by jorangreef** [comment]
Can you provide a small test case to reproduce?

**Comment by erguotou520** [comment]
I think this should be simple: https://github.com/erguotou520/sudo-prompt-with-builder

**Comment by jorangreef** [comment]
Thanks @erguotou520 

Can you please provide something which does not depend on Electron?

Just a single Node test script?

**Comment by jorangreef** [comment]
I want to remove as many variables as possible.

**Comment by erguotou520** [comment]
Oh, my issue is depended on Electron. Maybe need another project to do with Electron.

**Comment by erguotou520** [comment]
I thought this project is for Electron before. Sorry for that.

**Comment by jorangreef** [comment]
`sudo-prompt` works fine with Electron. I just want a minimal test script to reproduce. If your command works without Electron that gives more information to help debugging.

**Comment by erguotou520** [comment]
I think my repo is simple enough, no more dependency.
For develop, just run `npm run dev`.
For production, just run `npm run build`. It will create built files in build folder.

**Comment by erguotou520** [comment]
I want to know where is the `sudo-prompt-applet.zip` file? I can't find it in source. I think the issue is because this file is not included in the packaged file.

**Comment by jorangreef** [comment]
What version of `sudo-prompt` are you on?

It's here as a base64 encoded zip file which is unzipped to a temp path when you run `exec()`: https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L601

**Comment by erguotou520** [comment]
`^8.1.0`

**Comment by erguotou520** [comment]
Sorry, it's ok for Electron. I think my previous `flash back` issue was caused by rendering tray before app `ready`.  
Thanks for your contribution again for such useful project, especially the base64 zip file. 👍

**Comment by jorangreef** [comment]
Thanks @erguotou520 I am glad you could sort it out!

**Comment by erguotou520** [comment]
😺

**Comment by Dominic-Preap** [comment]
@jorangreef I have an issue where it doesn't popup dialog on Mac when app is codesign with electron-builder. But it is working fine in development or build the app without codesign.

```js
app.on('ready', () => {  
    const options = {  name: 'MyApp' };
    sudo.exec(`My Command`, options);
}
```

**Comment by Dominic-Preap** [comment]
@jorangreef very apologize. I misplace my icns file when build as production. Everything working fine right now. Thank you for your great works.
