### ISSUE TITLE
"Cannot find module --arg" on sudo.exec: C:/path/to/file.exe --arg

### ISSUE THREAD

**Issue by tylerssn** [jorangreef/sudo-prompt#68]
Firstly, thanks for this package. It has been great!

I am running into an issue when attempting to launch an exe file with args. In Power Shell I can execute `c:/path/to/file.exe --arg` and all runs well. When I try to execute using `sudo-prompt` with: 

```
sudo.exec('c:/path/to/file.exe --arg', options, config)
```

I receive the error: `Cannot find module --arg`

**Comment by jorangreef** [comment]
Thanks @tylerssn, would you be able to provide me with a minimal `test.js` file to reproduce on Windows?

**Comment by jorangreef** [comment]
@tylerssn have you come right with this?

I am closing for now, feel free to re-open. A minimal `test.js` would be appreciated.
