### ISSUE TITLE
[Windows] Doesn't work if executable in different disk than %TEMP%

### ISSUE THREAD

**Issue by frontierpsycho** [jorangreef/sudo-prompt#70]
`sudo-prompt` generates a batch file like the following on the fly:

```
@echo off
cd "path\to\executable"
"executable.exe" argument1 argument2
```

However, if the executable is in a different disk than the %TEMP% directory in Windows, then the cd line will fail to actually change the current working directory to where the executable is, as cd does not switch disks by default. Subsequently, sudo-prompt fails with a "could not find executable" error or somesuch.

To fix it, as discussed in [this SuperUser question](https://superuser.com/questions/413161/why-doesnt-cd-d-change-the-command-context-to-d), you need to add `/d`.

I'd do a pull request, but the change is trivial:

```
diff --git a/index.js b/index.js
index c74ecc6..203d702 100644
--- a/index.js
+++ b/index.js
@@ -559,7 +559,7 @@ function WindowsWriteCommandScript(instance, end) {
   script.push('@echo off');
   // Set code page to UTF-8:
   script.push('chcp 65001>nul');
-  script.push('cd "' + cwd + '"');
+  script.push('cd /d "' + cwd + '"');
   script.push(instance.command);
   script = script.join('\r\n');
   Node.fs.writeFile(instance.pathCommand, script, 'utf-8', end);
```

**Comment by jorangreef** [comment]
Thanks @frontierpsycho good catch.

I will do the PR shortly.

**Comment by jorangreef** [comment]
Fixed in https://github.com/jorangreef/sudo-prompt/commit/f677081dba73cd1785003d483137625de92dfab6
