### ISSUE TITLE
No polkit authentication agent found

### ISSUE THREAD

**Issue by LEKrensta** [jorangreef/sudo-prompt#72]
"stdout: "Error executing command as another user: No authentication agent found.\n" 

I seem to get this error when I try to execute a javascript file. I'm using a fresh install of linux on a VB and also tried installing polkit without any luck. Is there something I'm missing?

**Comment by jorangreef** [comment]
Thanks, what happens when you run `node_modules/sudo-prompt/test.js`?

**Comment by LEKrensta** [comment]
`sudo.exec("echo hello", {"name":"Electron"})
error: null
stdout: "hello\n"
stderr: ""
OK`

Is the following output for running test.js

My following code is as follows:
`debugConsole.log("Creating Service");
  
  try{
    sudo.exec('node createService.js', options,
    function(error, stderr, stdout){
      debugConsole.log('error: ' + error);
      debugConsole.log('stdout: ' + JSON.stringify(stdout));
      debugConsole.log('stderr: ' + JSON.stringify(stderr));
    });
  }catch(error){
    debugConsole.log(error);
  }
});`

Where createService installs a service file (which requires sudo). But I can't seem to get around this error.

**Comment by jorangreef** [comment]
It looks like you're receiving that error on `stdout`, which I think means it's an error that your `createService.js` is receiving.

If you saw a prompt when you ran `node_modules/sudo-prompt/test.js` then I think it's down to something in `createService.js` not in `sudo-prompt`.

**Comment by jorangreef** [comment]
Hope that helps you to narrow it down.

**Comment by LEKrensta** [comment]
A prompt does not show up when running the test file. I just get the output listed above.

**Comment by jorangreef** [comment]
Run `sudo -k` just before running the test file. Any change?

**Comment by LEKrensta** [comment]
Running `sudo -k` before running the test file still resulted in no prompt appearing.

**Comment by jorangreef** [comment]
The error you are receiving is from something that happens within `createService.js`. It's not an error returned to `sudo.exec()`, but something you're seeing in `stdout`.

Are you perhaps calling `sudo` again as part of a `childprocess.exec()` within `createService.js` (after you have already executed `createService.js` using `sudo.exec()`?

I don't think there's anything `sudo-prompt` can do here if the authentication agent is not installed.

I would recommend searching Linux issues for "No authentication agent found".
