### ISSUE TITLE
Broken on "obscure" platforms (such as NixOS)

### ISSUE THREAD

**Issue by Synthetica9** [jorangreef/sudo-prompt#77]
https://github.com/jorangreef/sudo-prompt/blob/52f82d0660515ec3b4189d3826422aa40c593599/index.js#L125

This assumes you know the exact location of the pkexec/kdesudo binary. This isn't always the case, for example on my (NixOS) system:

```
$ which pkexec
/run/wrappers/bin/pkexec
```

Would it be possible to use the environment to get the location of these executables?

**Comment by Synthetica9** [comment]
`which` would certainly be an option. I don't know if there are any node-specific ways of doing this the neatly.

**Comment by jorangreef** [comment]
Please try out this commit (not yet published to npm): https://github.com/jorangreef/sudo-prompt/commit/0e933b77c3e4f780236e137124eae31d867a80ad

Let me know if that fixes it.

**Comment by jorangreef** [comment]
It looks like NixOS does things differently with pkexec then, even once we've located the unusual bin path. I am sorry I don't have NixOS available to test. I'm going to revert the `which` commit until we know for sure and close this out, but if you can figure it out, please let me know.

**Comment by nh2** [comment]
There is a new PR at #123 -- it would be great if you could take a look!
