### ISSUE TITLE
Changelog?

### ISSUE THREAD

**Issue by subvertallchris** [jorangreef/sudo-prompt#78]
Hi Joran! Thank you for your work on this library, it's extremely useful for my work. I was wondering if there's a changelog somewhere? It'd be great to have as reference before updating. Perusing commits is fine when there are small numbers of changes but it could be tricky to do that quickly for some users, especially in the event of a larger update.

**Comment by jorangreef** [comment]
Thanks Chris! I almost always release after a single commit, but you're right, a CHANGELOG.md would be great. Would you be able to contribute a CHANGELOG.md covering the past releases and then I will take it from there?

**Comment by subvertallchris** [comment]
Sorry, seeing this close reminded me that I never got back to you. I'll slap together a quick changelog with at least the past couple months and a section for UNRELEASED and submit as PR when I have a moment today.
