### ISSUE TITLE
Setting plist using defaults

### ISSUE THREAD

**Issue by simpert** [jorangreef/sudo-prompt#79]
I am using sudo-prompt for many commands and mostly it has worked great. However, when I try to set plist entries using `defaults write myplist key val` the command seems to have worked as far as no errors thrown but the plist is never updated.

I can run the same command in a terminal using sudo and this works as expected. Also, I am aware newer version of Mac will not refresh cache so I run `pkill -f cfprefsd` after the plist commands to refresh.

For a test I also restart the machine just to see if it is a caching issue.

Any suggestions would be great. 

Thank You.

**Comment by jorangreef** [comment]
Thanks @simpert 

Can you please provide the full command you are giving `sudo-prompt`?

**Comment by jorangreef** [comment]
Or even better, a simple Node.js test script would be great.

**Comment by simpert** [comment]
sure

```  
const command = `defaults write com.adobe.CSXS.7 PlayerDebugMode 1 ; defaults read com.adobe.CSXS.7 ;`;
      

require('sudo-prompt').exec ( command,
                options,
               ( error, stdout, stderr ) =>
                {
                    if ( error )
                    {
                        reject ( error );
                    }

                    if ( stderr )
                        console.error(stderr);

                    this.raiseProgressChanged({ message: `done executing elevated command: '${command}' output: '${ stdout }'` });
                   
                    resolve ( true );
                } );
```

this is the code I am trying.
I place it in a promise and I am using typescript so I normally just use
```
import * as sudo from 'sudo-prompt';
```  
then use 
```
sudo.exec();
```
but since your expecting js I cleaned it up a bit.

I have used `sudo-prompt` before and in the same project am using it for several other commands all of which are working great. It seems a problem with `defaults` of sorts.

**Comment by simpert** [comment]
So I have been trying dozens of things and just now noticed there are many different scopes that `defaults` will write into. 
If I just open a terminal and type `defaults write com.adobe.CSXS.9 PlayerDebugMode 1` all works as expected.

**Comment by jorangreef** [comment]
Thanks @simpert 

I reduced your script to this:

```javascript
var sudo = require('.');
var command = 'defaults write com.adobe.CSXS.7 PlayerDebugMode 1; defaults read com.adobe.CSXS.7';
var options = {};
console.log('sudo.exec(' + JSON.stringify(command) + ', ' + JSON.stringify(options) + ')');
sudo.exec(command, options,
  function(error, stdout, stderr) {
    console.log('error: ' + error);
    console.log('stdout: ' + JSON.stringify(stdout));
    console.log('stderr: ' + JSON.stringify(stderr));
  }
);
```

This works for me on `macOS Mojave`, here is the output:

```
sudo.exec("defaults write com.adobe.CSXS.7 PlayerDebugMode 1; defaults read com.adobe.CSXS.7", {})
error: undefined
stdout: "{\n    PlayerDebugMode = 1;\n}\n"
stderr: ""
```

**Comment by jorangreef** [comment]
The test script above worked for me. Please re-open if you have more information.
