### ISSUE TITLE
Please include Applet’s AppleScript source code 

### ISSUE THREAD

**Issue by MikeSouza** [jorangreef/sudo-prompt#83]
Thank you for your work on this NPM package.

I was wondering if you could please include in this repo the AppleScript source code that the Applet application is compiled from?  It’s currently unnecessarily tedious to decode the base64 encoded zip file from `index.js`, write it to a file, and unzip it, just to audit the AppleScript `.scpt` file.

This is important for transparency and security auditing purposes.

NOTE:  This added source code could be put in a subdirectory such as `applet/`and excluded from the published NPM package using an `.npmignore` file.

Thanks.

**Comment by jorangreef** [comment]
> It’s currently unnecessarily tedious to decode the base64 encoded zip file from index.js, write it to a file, and unzip it, just to audit the AppleScript .scpt file.

Sure, the applet (which you can just open up in Xcode) was originally bundled separately, but was then included as a base64 string to work around an issue with Electron's ASAR format: https://github.com/jorangreef/sudo-prompt/issues/10

> NOTE: This added source code could be put in a subdirectory such as applet/and excluded from the published NPM package using an .npmignore file.

You would then still need to audit the included base64 string and the contents of the applet directory, to make sure they are in fact the same.

I am open to other suggestions. You are welcome to submit a PR for a script to parse the index.js file, decode the base64 and unzip and extract the .scpt file. But again, people would still need to trust the script.
