### ISSUE TITLE
Uncaught Error: User did not grant permission when trying to execute python script

### ISSUE THREAD

**Issue by lukechadwick** [jorangreef/sudo-prompt#86]
I'm trying to write a GUI for a python script for undervolting my laptop on linux, however when trying to run the command such as:

```
  readVoltage = () => {
    sudo.exec(
      'python /home/luke/workspace/undervolt-gui/undervolt/undervolt.py -r',
      options,
      function(error, stdout, stderr) {
        if (error) throw error;
        console.log('stdout: ' + stdout);
      }
    );
  };
```

I'm getting Uncaught Error: User did not grant permission when trying to execute python script. Am I doing things wrong?

**Comment by jorangreef** [comment]
Thanks @lukechadwick,

Can you try running `sudo-prompt/test.js` to test that `sudo-prompt` is working in your environment?

**Comment by jorangreef** [comment]
@lukechadwick , I am closing for lack of further information.

**Comment by jpeizer** [comment]
As opposed to opening a new ticket, I am running into the same thing with an electron application.

I'm on Linux trying to execute an elevated shell script from my app.  I am getting the following error...
```
stderr: pkexec must be setuid root
VM103:55 spawn error: Error: User did not grant permission.
```
Running the test.js returns permission denied.

Is there something that I'm missing in my setup that is preventing this from working as expected?

**Comment by jorangreef** [comment]
Your system `pkexec` binary either does not have the `setuid` bit set, or is not owned by the `root` user.

To find the path to your `pkexec` binary run: `which pkexec`

Then fix the permissions of the binary to have the `setuid` bit set, and make sure it is owned by the `root` user.

**Comment by jorangreef** [comment]
`pkexec` is what `sudo-prompt` uses on Linux systems to elevate privileges. This requires that `pkexec` itself has the power to do so.
