### ISSUE TITLE
return exit code

### ISSUE THREAD

**Issue by samuela** [jorangreef/sudo-prompt#87]
AFAICT there's no way to retrieve the exit code of the `exec`d command. This would be hugely beneficial. Just returning the `ChildProcess` would certainly solve this problem.

**Comment by jorangreef** [comment]
Please see the source, if the exit code is non-zero it is added to the returned error object:

https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L309
https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L481

**Comment by samuela** [comment]
Why not just always attach the exit code to the response object? That would make for a much more consistent API and one that is easier to use.

**Comment by jorangreef** [comment]
There is no response object.

"Just returning the `ChildProcess`" would not certainly solve this problem. Please see the README, past issues, and try to understand the source code for why we can't return the ChildProcess.

**Comment by samuela** [comment]
I did read the README and notice the "sudo-prompt.exec() is different to child-process.exec() in that no child process is returned (due to platform and permissions constraints)." bit but it's not clear to me exactly what those platform/permissions constraints are.

I see what you mean about not having an Error object to work with. What about a slightly different API along the lines of 
```typescript
sudo.exec('echo hello', options,
  (error, { exitCode: number, stdout: string, stderr: string }) => {
    if (error) throw error;
    console.log('Now I always no that the exit code will be: ' + exitCode);
    console.log('stdout: ' + stdout);
  }
);
```
