### ISSUE TITLE
`User did not grant permission.` error even after permission has been granted

### ISSUE THREAD

**Issue by samuela** [jorangreef/sudo-prompt#88]
I have a bit of code:
```typescript
  sudo.exec(
    `umount ${mountPath}`,
    { name: "nuvemfs" },
    (err: any, stdout: any, stderr: any) => {
      console.log("sudo complete");
      console.log("err");
      console.log(err);
      console.log("stdout");
      console.log(stdout);
      console.log("stderr");
      console.log(stderr);
    },
  );
```
that tries to unmount a drive. It throws up the prompt as expected and then prints the following:
```
sudo complete
err
Error: User did not grant permission.
    at /opt/nu-links/cli-node_modules/node_modules/sudo-prompt/index.js:111:23
    at ChildProcess.exithandler (child_process.js:282:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
stdout

stderr
umount: /home/darthvader/nu/skainswo: target is busy.
```
which doesn't make any sense since permission was in fact granted. It's just that the command returned a non-zero exit code.

**Comment by jorangreef** [comment]
Thanks @samuela , this is only on Linux and it should be fixed.

It's tricky to distinguish between `sudo`'s exit code and that of the command. `sudo` also translates its error messages depending on the locale (we used to work according to the these until we found that out).

**Comment by samuela** [comment]
@jorangreef Ah gotcha, I see how that could get messy. 

FWIW my hack is to execute `./my-actual-command.sh && echo "__UNIQUE_SUCCESS_MARKER__"` and check that `__UNIQUE_SUCCESS_MARKER__` shows up in stdout.
