### ISSUE TITLE
kill external program by sudo-prompt

### ISSUE THREAD

**Issue by abdurrahmanarikan** [jorangreef/sudo-prompt#90]
Hi
We want to kill the third party program which run by sudo-prompt before. But we have to use sudo-prompt again. It's not good to ask second time to user for having UAC permission. Is there any event listener to kill the program started by sudo-prompt or any other mechanism that we can stop asking UAC again?

**Comment by jorangreef** [comment]
Thanks @abdurrahmanarikan , I am sorry but that is beyond the scope of sudo-prompt, since we don't return a child process due to cross-platform complexity.

I would recommend rather communicating between your processes using simple files or sockets.
