### ISSUE TITLE
NodeJS script does not work on Linux due to Environment Variables not being preserved

### ISSUE THREAD

**Issue by jafri** [jorangreef/sudo-prompt#91]
It appears that both `kdesudo` and `pkexec` don't pass through environment variables, which makes `ELECTRON_RUN_AS_NODE=0` not work. This leads to the script trying to launch as a graphical command, which is obviously blocked.

**Comment by jafri** [comment]
Here is a fork with a working method of passing environment variables through `options.env`

https://github.com/jafri/sudo-prompt/commit/a066105d54d180eeffdf7b86cb814a0dee811f3a

**Comment by hacdias** [comment]
@jafri I'd like to see this working too for the same reason as you. Do you know if the environment variables are being preserved on other OSes?

**Comment by jafri** [comment]
You can try the async port at `exec-root`, it works on Windows and Linux with
```
{
      env: `ELECTRON_RUN_AS_NODE=0`
    }
```

**Comment by hacdias** [comment]
@jafri thanks! I'm just curious about how it works on Windows. I haven't seen any mention of `options.env` on Windows-related code.
