### ISSUE TITLE
What's the difference with...

### ISSUE THREAD

**Issue by y-nk** [jorangreef/sudo-prompt#92]
The original repo?
https://www.npmjs.com/package/sudo-prompt

**Comment by jorangreef** [comment]
I think you've figured it out, but there's no difference:

This is the git repo for the sudo-prompt npm package. You can see this also by following the repo link from the npm page you linked.

**Comment by y-nk** [comment]
@jorangreef actually i filled this here out of confusion, because i was coming from https://www.npmjs.com/package/@jafri/sudo-prompt which github link redirects to this repo (...and not @jafri 's one) - same with https://github.com/jafri/exec-root

**Comment by jorangreef** [comment]
Thanks @y-nk, yes I can't vouch for @jafri/sudo-prompt. That's someone else's fork.

This is the original repo. How did you come across @jafri/sudo-prompt?

**Comment by y-nk** [comment]
@jorangreef from the npmjs.org page. I guess it means that @jafri didn't change the repo url in his package.json fork before publishing.

**Comment by y-nk** [comment]
@jorangreef you can see it from here : https://unpkg.com/@jafri/sudo-prompt@8.2.5/package.json (L23)
