### ISSUE TITLE
Request permission once and run multiple commands

### ISSUE THREAD

**Issue by dekyfin** [jorangreef/sudo-prompt#95]
I have a gui app created with nwjs. The app needs to run several commands with elevated privileges. Using sudo-promt causes the password prompt to appear almost every time the user interacts with the app. Is there a way to request for elevated privliges once to run several commands?

**Comment by jorangreef** [comment]
Due to TTY tickets we can't solve this from `sudo-prompt`, however, you can put your commands into a single script, which you then run with `sudo-prompt`.

**Comment by dekyfin** [comment]
Thanks for the response. Unfortunately, the commands are independently
triggered by the user. This makes it impossible to put everything in one
script.

**Comment by actuallymentor** [comment]
@jorangreef is this entirely out of scope for this package?

For use in GUI apps (e.g. Electron) it would be convenient to be able to do something like:

```js
const sudo = require('sudo-prompt')

// This would prompt the user
const su = sudo.init( { ...options } )

// This would execute a command with sudo but with the cached permissions
su.exec( 'echo 1' , ( err, stderr, stdout ) => manageoutput( err, stderr, stdout ) )
```

Currently this package is great for incidental commands, but in GUIs it results in @dekyfin's example of a prompt after every button press that requires sudo.

**Comment by jorangreef** [comment]
@actuallymentor, yes it's out of scope.

It's not possible on any platform to cache permissions because of TTY tickets on Linux and Mac, and how we elevate on Windows.
