### ISSUE TITLE
Cancelation fails on windows for non english users

### ISSUE THREAD

**Issue by zvin** [jorangreef/sudo-prompt#96]
[The code](https://github.com/jorangreef/sudo-prompt/blob/master/index.js#L451) checks for `canceled by the user` but this message depends on the language.

French for example: `Impossible d'exécuter cette commande en raison de l'erreur: L'opération a été annulée par l'utilisateur`

**Comment by jorangreef** [comment]
Thanks @zvin, anything else we can use on Windows to check? We ran into this on Linux in the past.

**Comment by zvin** [comment]
We use `GetLastError() == ERROR_CANCELLED` in a native module here https://github.com/balena-io/etcher/blob/master/src/os/win32/elevate.cpp#L87 , I'm not sure we can get this from powershell or cmd. Or maybe there's a way to force the message to be in English?

**Comment by jorangreef** [comment]
Another way might be for us to wrap the user command in its own shell script, so that we can distinguish between runAs errors and user command errors. We do this for Mac and need to do this for Linux.

**Comment by jorangreef** [comment]
If you can give me a few days, I will work on this.
