### ISSUE TITLE
Error code -60005 (macOS)

### ISSUE THREAD

**Issue by debelop13** [jorangreef/sudo-prompt#98]
Hi,

When sudo-prompt.exec is executed it gives and strange error -6005.

It says that the user admin o the password are incorrect. But it didn't ask for user and password.

What can be?

Thanks

**Comment by jorangreef** [comment]
Thanks @debelop13, could you please provide more information:

1. Platform
2. Stderr, Stdout
3. Screenshot
4. Script to reproduce

**Comment by jorangreef** [comment]
Closing for lack of further information.
